[package]
name = "advent_of_code2016"
version = "0.1.0"
authors = ["Fredrik Jansson <frjansso@cisco.com>"]

[dependencies]
combine = "*"
regex = "*"
lazy_static = "*"
astar = { path = "../astar" }
permutate = "*"
permutohedron = "*"
